version: "3.8"
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - siwe_demo_postgres:/var/lib/postgresql/data

volumes:
  siwe_demo_postgres: